<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseRegistrationFormType;

class RegistrationFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('username', HiddenType::class );
    }

    /**
     * @return null|string
     */
    public function getBlockPrefix()
    {
        return 'app_bundle_registration_form_type';
    }

    /**
     * @return null|string
     */
    public function getParent()
    {
        return BaseRegistrationFormType::class; // TODO: Change the autogenerated stub
    }
}
